import Mathlib.LinearAlgebra.Dimension.Finrank
import Mathlib.LinearAlgebra.Matrix.Notation
import Mathlib.Tactic
import Penumbra.MobiusSO4Embedding
import Penumbra.SO4Decomposition
import HeytingLean.Core.Nucleus

/-!
# Penumbra.AntiSelfDualProjection

The concrete self-dual/anti-self-dual projections on the Penumbra `so(4)` model are exact
idempotent linear-algebra operations. The anti-self-dual triple and the self-dual triple are
each linearly independent, and every skew-coordinate matrix decomposes into the sum of its
self-dual and anti-self-dual parts.

This gives the honest codimension witness available on the current concrete surface: inside the
six-coordinate skew subspace generated by `skewOfCoords`, the anti-self-dual factor is a
3-dimensional exact locus rather than an approximate basin.

The structural analogy with a Heyting nucleus is recorded here only as motivation. This module
does **not** instantiate `HeytingLean.Core.Nucleus` on `SO4`, because the ambient object here is a
vector space rather than a lattice. A genuine bridge would live on the lattice of subspaces.
-/

namespace Penumbra

open Matrix

/-- The anti-self-dual basis as a `Fin 3` family. -/
def antiSelfDualBasis : Fin 3 → SO4
  | 0 => j1Minus
  | 1 => j2Minus
  | 2 => j3Minus

/-- The self-dual basis as a `Fin 3` family. -/
def selfDualBasis : Fin 3 → SO4
  | 0 => j1Plus
  | 1 => j2Plus
  | 2 => j3Plus

/-- `plusProjection` is exactly idempotent. -/
theorem plusProjection_idempotent (A : SO4) :
    plusProjection (plusProjection A) = plusProjection A := by
  ext i j
  fin_cases i <;> fin_cases j <;> (simp [plusProjection]; try ring_nf)

/-- `minusProjection` is exactly idempotent. -/
theorem minusProjection_idempotent (A : SO4) :
    minusProjection (minusProjection A) = minusProjection A := by
  ext i j
  fin_cases i <;> fin_cases j <;> (simp [minusProjection]; try ring_nf)

/-- The Möbius generator lies in the kernel of the self-dual projection. -/
theorem mobius_in_plusProjection_kernel :
    plusProjection mobiusGenerator = 0 :=
  (mobius_projection_split).1

/-- The Möbius generator is fixed by the anti-self-dual projection. -/
theorem mobius_is_minusProjection_fixed :
    minusProjection mobiusGenerator = mobiusGenerator := by
  simpa [j1Minus] using (mobius_projection_split).2

/-- Each anti-self-dual basis element lies in the kernel of `plusProjection`. -/
theorem anti_self_dual_in_plusProjection_kernel (a b c : ℝ) :
    plusProjection (a • j1Minus + b • j2Minus + c • j3Minus) = 0 := by
  simpa using plusProjection_of_minus_combination a b c

/-- Every anti-self-dual combination is fixed by `minusProjection`. -/
theorem anti_self_dual_combination_is_minus_fixed (a b c : ℝ) :
    minusProjection (a • j1Minus + b • j2Minus + c • j3Minus) =
      a • j1Minus + b • j2Minus + c • j3Minus := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    (simp [minusProjection, j1Minus, j2Minus, j3Minus, mobiusGenerator]; try ring_nf)

/-- Every self-dual combination is fixed by `plusProjection`. -/
theorem self_dual_in_plusProjection_image (a b c : ℝ) :
    plusProjection (a • j1Plus + b • j2Plus + c • j3Plus) =
      a • j1Plus + b • j2Plus + c • j3Plus := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    (simp [plusProjection, j1Plus, j2Plus, j3Plus]; try ring_nf)

/-- Every self-dual combination lies in the kernel of `minusProjection`. -/
theorem self_dual_in_minusProjection_kernel (a b c : ℝ) :
    minusProjection (a • j1Plus + b • j2Plus + c • j3Plus) = 0 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    (simp [minusProjection, j1Plus, j2Plus, j3Plus]; try ring_nf)

/-- The anti-self-dual triple is linearly independent. -/
theorem anti_self_dual_basis_lin_indep :
    LinearIndependent ℝ antiSelfDualBasis := by
  refine linearIndependent_iff_injective_fintypeLinearCombination.2 ?_
  intro a b hab
  ext i
  fin_cases i
  · have h01 := congrArg (fun M => M 0 1) hab
    simpa [Fintype.linearCombination, Fin.sum_univ_three, antiSelfDualBasis,
      j1Minus, j2Minus, j3Minus, mobiusGenerator]
      using h01
  · have h02 := congrArg (fun M => M 0 2) hab
    simpa [Fintype.linearCombination, Fin.sum_univ_three, antiSelfDualBasis,
      j1Minus, j2Minus, j3Minus, mobiusGenerator]
      using h02
  · have h03 := congrArg (fun M => M 0 3) hab
    simpa [Fintype.linearCombination, Fin.sum_univ_three, antiSelfDualBasis,
      j1Minus, j2Minus, j3Minus, mobiusGenerator]
      using h03

/-- The self-dual triple is linearly independent. -/
theorem self_dual_basis_lin_indep :
    LinearIndependent ℝ selfDualBasis := by
  refine linearIndependent_iff_injective_fintypeLinearCombination.2 ?_
  intro a b hab
  ext i
  fin_cases i
  · have h01 := congrArg (fun M => M 0 1) hab
    simpa [Fintype.linearCombination, Fin.sum_univ_three, selfDualBasis, j1Plus, j2Plus, j3Plus]
      using h01
  · have h02 := congrArg (fun M => M 0 2) hab
    simpa [Fintype.linearCombination, Fin.sum_univ_three, selfDualBasis, j1Plus, j2Plus, j3Plus]
      using h02
  · have h03 := congrArg (fun M => M 0 3) hab
    simpa [Fintype.linearCombination, Fin.sum_univ_three, selfDualBasis, j1Plus, j2Plus, j3Plus]
      using h03

/-- Every skew-coordinate matrix splits exactly into its self-dual and anti-self-dual parts. -/
theorem so4_splits_as_plus_minus (a01 a02 a03 a12 a13 a23 : ℝ) :
    plusProjection (skewOfCoords a01 a02 a03 a12 a13 a23) +
      minusProjection (skewOfCoords a01 a02 a03 a12 a13 a23) =
      skewOfCoords a01 a02 a03 a12 a13 a23 := by
  simpa using plus_minus_recompose_coords a01 a02 a03 a12 a13 a23

/-- Honest summary theorem: exact projection facts on the concrete skew-coordinate surface. -/
theorem anti_self_dual_projection_properties :
    (∀ A, minusProjection (minusProjection A) = minusProjection A) ∧
    (minusProjection mobiusGenerator = mobiusGenerator) ∧
    LinearIndependent ℝ antiSelfDualBasis ∧
    LinearIndependent ℝ selfDualBasis ∧
    (∀ a01 a02 a03 a12 a13 a23,
      plusProjection (skewOfCoords a01 a02 a03 a12 a13 a23) +
        minusProjection (skewOfCoords a01 a02 a03 a12 a13 a23) =
        skewOfCoords a01 a02 a03 a12 a13 a23) := by
  exact ⟨minusProjection_idempotent,
    mobius_is_minusProjection_fixed,
    anti_self_dual_basis_lin_indep,
    self_dual_basis_lin_indep,
    so4_splits_as_plus_minus⟩

end Penumbra
